Documentation for CREATE SEQUENCE
YugaByte/docs pull request #12
Opened 2019-02-27 00:41 UTC by hectorgcr

2019-02-27 23:02 UTC, hectorgcr commented
To make it easier to review the code, you can see the new documentation here: http://10.150.0.4:35493/latest/api/ysql/

2019-02-28 01:29 UTC, ravimurthy commented on content/latest/api/ysql/_index.md
> +## Sequences
How about DROP SEQUENCE?

2019-02-28 01:29 UTC, ravimurthy commented on content/latest/api/ysql/create_sequence.md
> +In YSQL as in Postgres, the sequence's data is stored in two values: `last_val` and `is_called`. `last_val` stores the last value allocated for that sequence. When `is_called` is false indicates that
Clarify that sequence data is stored in a persistent system table. The table has one row per sequence - and stores last_val and is_called. List out the two columns and their semantics 
last_val - ...
is_called - ....

2019-02-28 01:29 UTC, ravimurthy commented on content/latest/api/ysql/create_sequence.md
> +By default (when `INCREMENT` is 1), each call to `nextval()` updates `last_val` for that sequence. In YSQL, the table holding the sequence's data is replicated as opposed to being in the local file s
... requires two RPCs currently (and will be optimized to 1 RPC in the future). In any case, latency will be significantly higher...

2019-02-28 01:29 UTC, ravimurthy commented on content/latest/api/ysql/create_sequence.md
> +By default (when `INCREMENT` is 1), each call to `nextval()` updates `last_val` for that sequence. In YSQL, the table holding the sequence's data is replicated as opposed to being in the local file s
Mention that the cached values are stored in memory on the localnode, and avoids the RPC.

2019-03-01 03:50 UTC, hectorgcr commented
Addressed @ravimurthy comments.
New server running on http://10.150.0.4:42626/latest/api/ysql/

2019-03-02 00:17 UTC, hectorgcr commented
Added a note about `ALTER SEQUENCE` and `setval()` not being supported yet

2019-03-04 19:22 UTC, ndeodhar requested changes

2019-03-04 19:22 UTC, ndeodhar commented on content/latest/api/ysql/_index.md
> +[`currval(sequence)`](currval_sequence) | Get the last value returned by a nextval call
```suggestion
[`currval(sequence)`](currval_sequence) | Get the last value returned by the most recent nextval call for the specified sequence
```

2019-03-04 19:22 UTC, ndeodhar commented on content/latest/api/ysql/_index.md
> +[`lastval()`](lastval_sequence) | Get the last value returned by any nextval call
```suggestion
[`lastval()`](lastval_sequence) | Get the last value returned by the most recent nextval call for any sequence
```

2019-03-04 19:22 UTC, ndeodhar commented on content/latest/api/ysql/create_sequence.md
> +create_sequence = 'CREATE' 'SEQUENCE' [ 'IF' 'NOT' 'EXISTS' ] sequence_name sequence_options;
I think we can remove the single quotes around 'CREATE', 'SEQUENCE' etc. - keep it consistent with how we've specified INSERT/SELECT statements.
(Same comment applies below for DROP SEQUENCE also).

2019-03-04 19:22 UTC, ndeodhar commented on content/latest/api/ysql/create_sequence.md
> +sequence_options = [ 'INCREMENT' [ 'BY' ] increment ] [ 'MINVALUE' minvalue | 'NO' 'MINVALUE' ] [ 'MAXVALUE' maxvalue | 'NO' 'MAXVALUE' ] [ 'START' [ 'WITH' ] start ] [ 'CACHE' cache ];
START WITH and CACHE are going outside of the gray box when you view this.

2019-03-04 19:22 UTC, ndeodhar commented on content/latest/api/ysql/create_sequence.md
> +- `cache` how many numbers from the sequence to cache in the client. Default is 1.
nit (to keep sentence construction similar):
```suggestion
- `cache` specifies how many numbers from the sequence to cache in the client. Default is 1.
```

2019-03-04 19:22 UTC, ndeodhar commented on content/latest/api/ysql/create_sequence.md
> +- An error is raised if a sequence with that name already exists in the current schema.
```suggestion
- An error is raised if a sequence with that name already exists in the current schema and `IF NOT EXISTS` is not specified.
```

2019-03-04 19:22 UTC, ndeodhar commented on content/latest/api/ysql/create_sequence.md
> +CREATE TABLE t(k integer NOT NULL DEFAULT nextval('t_k_seq');
Missing ending parenthesis.
```suggestion

CREATE TABLE t(k integer NOT NULL DEFAULT nextval('t_k_seq'));
```

2019-03-04 19:22 UTC, ndeodhar commented on content/latest/api/ysql/create_sequence.md
> +Create a sequence that starts at 0. MINVALUE also has to be changed from its default 1 to something less than or equal to 0.
This should also be mentioned above where you are describing MINVALUE and START.

2019-03-04 19:22 UTC, ndeodhar commented on content/latest/api/ysql/drop_sequence.md
> +- An error is raised if a sequence with that name already exists in the current schema.
```suggestion
- An error is raised if a sequence with that name does not exist in the current schema unless `IF EXISTS` is specified.
```

2019-03-05 00:03 UTC, ndeodhar requested changes
Minor comments - LGTM otherwise.

2019-03-05 00:03 UTC, ndeodhar commented on content/latest/api/ysql/currval_sequence.md
> +currval ::= SELECT currval'(' sequence_name ')';
Remove the single quotes similar to what you've done elsewhere.
```suggestion
currval ::= SELECT currval( sequence_name );
```

2019-03-05 00:03 UTC, ndeodhar commented on content/latest/api/ysql/lastval_sequence.md
> +lastval ::= SELECT lastval'()';
```suggestion
lastval ::= SELECT lastval();
```

2019-03-05 00:03 UTC, ndeodhar commented on content/latest/api/ysql/nextval_sequence.md
> +nextval ::= SELECT nextval'(' sequence_name ')';
```suggestion
nextval ::= SELECT nextval( sequence_name );
```

2019-03-05 00:55 UTC, ndeodhar approved these changes

2019-03-05 00:56 UTC, merged